### ISSUE TITLE
Hello i got some error what is the problem with this 

### ISSUE THREAD

**Issue by Tomz10105** [ryanio/opensea-activity-bot#2]
const shortAddr = (addr) => addr.slice(0, 7) + '...' + addr.slice(37, 42);
                                 ^

TypeError: Cannot read properties of undefined (reading 'slice')

**Comment by ryanio** [comment]
Hm is there a longer stack trace to see where the address is undefined?

**Comment by Tomz10105** [comment]
> Hm is there a longer stack trace to see where the address is undefined?

only that error i got do you have discord? ill send you my .env

**Comment by ryanio** [comment]
can you try to set INFURA_PROJECT_ID, you should be able to sign up for a free account, if that fixes it then i can probably track it down

**Comment by Tomz10105** [comment]
> can you try to set INFURA_PROJECT_ID, you should be able to sign up for a free account, if that fixes it then i can probably track it down

i also put that one only twitter i didnt put since ill use only the discord

**Comment by ryanio** [comment]
ah okay thanks. ok i'm tracing the code, did you define `TOKEN_ADDRESS` in your env file? it needs to be defined and accessible via `process.env.TOKEN_ADDRESS`. you can try to add a console log one line above [here](https://github.com/ryanio/opensea-activity-bot/blob/555270fd4edbd1e2da7e2282f9d1fe96066e8a70/src/util.ts#L112) to check if it is defined at run-time.

**Comment by Tomz10105** [comment]
> ah okay thanks. ok i'm tracing the code, did you define `TOKEN_ADDRESS` in your env file? it needs to be defined and accessible via `process.env.TOKEN_ADDRESS`. you can try to add a console log one line above [here](https://github.com/ryanio/opensea-activity-bot/blob/555270fd4edbd1e2da7e2282f9d1fe96066e8a70/src/util.ts#L112) to check if it is defined at run-time.

i also put the token_address .. the token address is the contract address right

**Comment by Tomz10105** [comment]
const shortAddr = (addr) => addr.slice(0, 7) + '...' + addr.slice(37, 42);
                                 ^

TypeError: Cannot read properties of undefined (reading 'slice')
    at shortAddr (C:\Users\Administrator\Desktop\opensea-activity-bot-master\dist\util.js:30:34)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\opensea-activity-bot-master\dist\util.js:104:48)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\opensea-activity-bot-master\dist\discord.js:7:16)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)

Node.js v18.15.0

**Comment by Tomz10105** [comment]
on my .env 

OPENSEA_API_TOKEN=
TOKEN_ADDRESS=
INFURA_PROJECT_ID=
DISCORD_EVENTS=
DISCORD_TOKEN=

**Comment by ryanio** [comment]
@Tomz10105 it seems to be an issue with the env variables not being available. are you running `source .env` before running? maybe try adding `export` to each line like so:
```
export OPENSEA_API_TOKEN=
export TOKEN_ADDRESS=
export INFURA_PROJECT_ID=
export DISCORD_EVENTS=
export DISCORD_TOKEN=
```
then try running again. let me know if that helps.
in your console what returns if you type `echo $TOKEN_ADDRESS`

**Comment by Tomz10105** [comment]
how to get the lastEventId 
   throw err;
    ^

SyntaxError: C:\Users\Administrator\Desktop\opensea-activity-bot-master\dist\meta.json: Unexpected token ' in JSON at position 0

**Comment by ryanio** [comment]
sorry about the trouble, can you try again? if you have any problem please just open a new issue with details how to reproduce the issue
